development:
  sessions:
    default:
      #database: iObserveService
      database: visitracker_backup
      hosts:
        - localhost
      options:
        consistency: :strong
  options:
    identity_map_enabled: true
    raise_not_found_error: false
  options:

#development:
# sessions:
#   default:
#     database: heroku_app15673847
#     hosts:
#       - ds029847.mongolab.com:29847
#     username: rich
#     password: MonkeyM78
#     options:
#       consistency: :strong
# options:

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
  options:
    identity_map_enabled: true
    raise_not_found_error: false